---
- name: Настройка сбора метрик MySQL
  hosts: carrier
  become: true

  vars_files:
    - vars/wordpress.yml
    - vars/monitoring.yml

  tasks:
    - name: Проверка подключения к кластеру
      ansible.builtin.import_tasks: tasks/mysql/mysql_connections.yml

    - name: Создание пользователей мониторинга
      ansible.builtin.import_tasks: tasks/monitoring/mysql_monitoring_users.yml

    - name: Запуск экспортёров метрик MySQL
      ansible.builtin.import_tasks: tasks/monitoring/mysql_exporters.yml

    - name: Настройка Prometheus
      ansible.builtin.import_tasks: tasks/monitoring/prometheus.yml
