---
- name: Подготовка основного MySQL и реплики
  hosts: carrier
  become: true

  vars_files:
    - vars/wordpress.yml

  tasks:
    - name: Подготовка основного сервера MySQL
      ansible.builtin.import_tasks: tasks/mysql.yml
      vars:
        mysql_command: >-
          --server-id=1
          --log-bin=mysql-bin
          --binlog-format=ROW

    - name: Подготовка реплики MySQL
      ansible.builtin.import_tasks: tasks/mysql_replica.yml
