---
- name: Установка Docker и запуск WordPress
  hosts: carrier
  become: true

  vars_files:
    - vars/wordpress.yml

  tasks:
    - name: Подготовка Docker
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Подготовка MySQL
      ansible.builtin.import_tasks: tasks/mysql.yml

    - name: Подготовка WordPress
      ansible.builtin.import_tasks: tasks/wordpress.yml
