---
- name: Установка Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-requests
    state: present
    update_cache: true

- name: Запуск службы Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Создание сети для контейнеров
  community.docker.docker_network:
    name: wordpress_network